[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
atoi = "2.0.0"
itertools = "0.13.0"
memchr = "2.7.4"
nom = "7.1.3"
regex = "1.11.1"
