name: CodSpeed

on:
  push:
    branches:
      - "master"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          channel: nightly-2024-12-02
          cache-target: release
          bins: cargo-codspeed
      - name: Install cargo-aoc
        run: cargo install --rev 81c765bc0e697ed8f64cc1ebd27b2480fc633483 --git https://github.com/david-a-perez/cargo-aoc cargo-aoc
      
      - name: Auto-generate and run benchmarks
        run: cargo aoc bench --all-days

      - name: You need to install the criterion.rs compatibility layer
        working-directory: ./target/aoc/aoc-autobench/
        run: cargo add --dev codspeed-criterion-compat --rename criterion

      - name: Build the benchmark target(s)
        working-directory: ./target/aoc/aoc-autobench/
        run: cargo codspeed build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          working-directory: ./target/aoc/aoc-autobench/
          token: ${{ secrets.CODSPEED_TOKEN }}